filebeat.modules:
- module: apache2
- module: auditd
- module: mysql
- module: nginx
- module: system


filebeat.inputs:
- type: log
  paths:
    - /var/log/app.log
  fields_under_root: true
  fields:
    application: app
- type: log
  paths:
    - /var/log/apache2/modsec_audit.log
  json:
    keys_under_root: true
    add_error_key: true
  fields_under_root: true
  fields:
    application: mod_security


name: "{{ inventory_hostname }}"
tags: ["{{ env }}", "lightsail"]


processors:
- add_cloud_metadata: ~
- add_host_metadata: ~
# Rename the ModSecurity JSON field so it can be displayed in the Logs UI
- rename:
    when:
      equals:
        application: mod_security
    fields:
     - from: "audit_data.error_messages"
       to: "message"
    ignore_missing: true
    fail_on_error: false


monitoring.enabled: true


output.elasticsearch:
  hosts: ["{{ elasticsearch_host }}"]
  username: "{{ elasticsearch_user }}"
  password: "${ES_PWD}"


setup:
  kibana:
    host: "{{ kibana_host }}"
    username: "{{ elasticsearch_user }}"
    password: "${ES_PWD}"
  ilm.overwrite: true
