heartbeat.monitors:

- type: http
  urls: ["https://{{ domain }}"]
  schedule: "@every 10s"
  timeout: 3s
  check.response.status: 200

- type: http
  urls: ["https://{{ domain }}:8080"]
  schedule: "@every 10s"
  timeout: 3s
  check.response.status: 200

- type: tcp
  name: MySQL
  schedule: "@every 10s"
  hosts: ["localhost:3306"]


name: "{{ inventory_hostname }}"
tags: ["{{ env }}", "lightsail"]


processors:
- add_cloud_metadata: ~
- add_host_metadata: ~


monitoring.enabled: true


output.elasticsearch:
  hosts: ["{{ elasticsearch_host }}"]
  username: "{{ elasticsearch_user }}"
  password: "${ES_PWD}"


# No setup because the Uptime Monitoring is already built into Kibana
